config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  root to: 'home#index'

  match ':status', to: 'errors#show', constraints: { status: /\d{3}/ }, via: [:get, :post]
  resource :profile, except: :index do
    get :active
    get :disable
  end
  resources :timelines, only: :show
  get 'timelines/:id/monthly/:date' => 'timelines#monthly', as: :timeline_monthly
  constraints(id: /\d+/) do
    resources(:posts, only: [:show, :index])
  end
  resources(:articles, only: [:show, :index]) do
    collection do
      scope :categories do
        get ':category_id', to: 'articles#index', as: :categories
      end
    end
    get :raw, on: :member
  end

  resources :partners, only: :show
  get 'articles/page/:page_id' => 'articles#index', as: :paged_articles
  resources(:tags, param: :name, only: []) { resources :articles, only: :index }
  resources(:categories) { resources :articles, only: :index }
  get :colaborators, to: 'static_pages#colaborators'
  resources :authors, only: :show
  resources :pages, only: :show
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  namespace :api do
    resources :credentials, only: :create
    post 'credentials/update_social_network_id' => 'credentials#update_social_network_id'
    post 'check_numbers' => 'message_deliveries#check_numbers'
    resources :device_registrations, only: [:create, :show, :destroy], id: /[^\/]+/, param: :platform_code
    resources :messages, only: :show
    resources :profiles, only: [:index]
    get 'active_profile' => 'profiles#active'
    get 'disable_profile' => 'profiles#disable'
    post 'profiles/max_recipient_children' => 'profiles#update_max_recipient_children'
    post "profiles" => 'profiles#update'
    resources :donated_messages, only: [:index]
    post 'donated_messages/mark_as_sent' => 'donated_messages#mark_as_sent'
    resources :children, only: :index
    post 'd3d4b74ea38c163c820cd84b25f5/a8eecbf2d604ff6769fd64f1a492' => 'message_deliveries#create'
    devise_scope :user do
      post "/users" => 'users#create'
      post '/users/reset_password' => 'passwords#create'
    end
    get 'birthday_cards/show' => 'birthday_cards#show'
    get 'only_new_messages' => 'messages#only_new'
    resources :categories, only: [:index]
  end

  mount_carnival_at 'admin'
  namespace :admin do
    authenticate :user, ->(u) { u.admin? }  do
      mount Sidekiq::Web => '/sidekiq'
    end
    resources :activity_logs, only: [:index, :show]
    resources :admin_site_users
    resources :articles
    resources :posts
    resources :authors
    resources :categories
    resources :messages
    resources :message_deliveries, only: :index
    resources :profiles
    resources :site_banners
    resources :site_headers
    resources :site_landing_pages
    resources :site_mobile_images
    resources :partners
    resources :site_users do
      get :authorize_receive_sms, on: :member
      get :unauthorize_receive_sms, on: :member
      get :active_profile, on: :member
      get :disable_profile, on: :member
    end
    resources :tags
    resources :birthday_cards
    resources :pages
    resources :menus
    resources :engines
    resources :manager_message_deliveries, only: :index
    resources :searchlogs
    resources :sms_responses
    get 'articles/:id/show_activity_log' => 'articles#show_activity_log'
    get 'site_users/:id/stop_impersonating' => 'site_users#stop_impersonating', as: :stop_impersonating
    get 'admin_site_users/:id/edit_profile' => 'admin_site_users#edit_profile', as: :edit_profile
    get 'site_users/:id/impersonate' => 'site_users#impersonate', as: :impersonate_user

    get 'gallery_images' => 'gallery_images#index'

    post 'new_image' => 'cms_images#create'
  end
end

app/models/articles/article.rb
module Articles
  class Article < ActiveRecord::Base
    include Carnival::ModelHelper
    include RejectAttributesConcern
    include Searchable
    extend FriendlyId

    friendly_id :title, use: :slugged

    GENDER_ENUM = [:male, :female, :both]
    BABY_TARGET_TYPE_ENUM = [:pregnancy, :born]
    CHILD_LIFE_PERIOD_ENUM = [:first_to_fourth, :fifth_to_eighth,
                              :nineth_to_twelfth, :thirteenth_to_eighteenth]

    enum baby_target_type: BABY_TARGET_TYPE_ENUM
    enum child_life_period: CHILD_LIFE_PERIOD_ENUM
    enum gender: GENDER_ENUM


    belongs_to :cover_picture, class_name: 'Ckeditor::Asset'
    belongs_to :thumb_picture, class_name: 'Ckeditor::Asset'
    belongs_to :category
    belongs_to :original_author, class_name: 'Authors::Author'
    belongs_to :user
    has_and_belongs_to_many :tags
    # has_and_belongs_to_many :tags, after_add:    [ lambda { |a,c| a.__elasticsearch__.index_document } ],
    #                                    after_remove: [ lambda { |a,c| a.__elasticsearch__.index_document } ]
    has_many :article_references
    has_many :messages

    accepts_nested_attributes_for :messages, reject_if: all_blank?(:text), allow_destroy: true
    accepts_nested_attributes_for :article_references, allow_destroy: true
    accepts_nested_attributes_for :tags, allow_destroy: false

    validates :text, :title, :category, :user, :original_author, presence: true
    validates :baby_target_type, :gender, presence: true, if: :category_is_not_blog_section?
    validates :title, uniqueness: { case_sensitive: false }

    validate :minimum_not_higher_than_maximum
    validate :category_is_a_subcategory
    validate :presence_of_maximum_or_minimum
    validate :length_of_messages

    before_validation :ensure_presence_of_original_author
    before_save :set_defaults
    before_save :update_child_life_period
    after_save :update_messages

    delegate :name, to: :category, prefix: true
    delegate :color, to: :category, prefix: true
    delegate :name, to: :original_author, prefix: true

    has_paper_trail

    def presence_of_maximum_or_minimum
      return if !category_is_not_blog_section?
      return unless minimum_valid_week.blank? && maximum_valid_week.blank?
      errors.add(:base, :has_no_minimum_and_maximum_valid_week)
    end

    def minimum_not_higher_than_maximum
      return unless minimum_valid_week.present? && maximum_valid_week.present?
      return unless minimum_valid_week > maximum_valid_week
      errors.add(:base, :minimum_higher_than_maximum)
    end

    def set_defaults
      self.baby_target_type ||= 'pregnancy'
    end

    def born?
      baby_target_type == 'born'
    end

    def pregnancy?
      !born?
    end

    def tag_names
      tags.map(&:name).join(', ')
    end

    def tag_names=(tag_names)
      split_tag_names = Articles::TagSplitter.new(tag_names).split_by_comma
      self.tags =
        Articles::TagByNameCreator.new(split_tag_names)
        .find_or_create_tags
    end

    def thumb_image_cover
      return self.thumb_picture.data if self.thumb_picture.present?
    end

    def cover
      return self.cover_picture.data if self.cover_picture.present?
    end

    def should_generate_new_friendly_id?
      new_record? || title_changed? || slug.nil?
    end

    protected

    def category_is_a_subcategory
      return if category.try(:subcategory?)
      errors.add(:category, :should_be_subcategory)
    end

    def update_messages
      Articles::MessageUpdater.update_many_from_article(messages, self)
    end

    def length_of_messages
      return unless messages.find { |message| message.text_size > 150 }
      errors.add(:base, :messages_length)
    end

    def update_child_life_period
      return unless born?
      self.child_life_period = Children::LifePeriodForWeek
        .new(minimum_valid_week, maximum_valid_week).life_period
    end

    def ensure_presence_of_original_author
      self.original_author ||= Authors::DefaultAuthor.find_default_author
    end

    def category_is_not_blog_section?
      return true if self.category.nil?
      return true if self.category.parent_category.nil?
      !self.category.parent_category.blog_section
    end
  end
end

Articles::Article.__elasticsearch__.client = Elasticsearch::Client.new host: ProBebeConfig.elasticsearch_host, log: true if Rails.env != 'test'

app/models/articles/article_reference.rb
class Articles::ArticleReference < ActiveRecord::Base
  include Carnival::ModelHelper

  belongs_to :article
end

app/models/articles/article_with_image_cover.rb
module Articles
  class ArticleWithImageCover < Article
    validates :cover_picture, presence: true

    def self.model_name
      Article.model_name
    end

    def self.sti_name
      Article.sti_name
    end
  end
end

app/models/articles/message_updater.rb
module Articles
  class MessageUpdater

    def self.update_from_article(message, article)
      message.gender = article.gender
      message.teenage_pregnancy = article.teenage_pregnancy
      message.baby_target_type = article.baby_target_type
      message.minimum_valid_week = article.minimum_valid_week
      message.maximum_valid_week = article.maximum_valid_week
      message.category = article.category
      message.save!
    end

    def self.update_many_from_article(messages, article)
      messages.each do |message|
        update_from_article(message, article)
      end
    end

  end
end

app/models/articles/tag_by_name_creator.rb
module Articles
  class TagByNameCreator
    def initialize(tag_names)
      @tag_names = tag_names
    end

    def find_or_create_tags
      @tag_names.map do |tag_name|
        Tag.find_or_create_by(name: tag_name)
      end
    end
  end
end

app/models/articles/tag_splitter.rb
module Articles
  class TagSplitter
    def initialize(tag_text)
      @tag_text = tag_text
    end

    def split_by_comma
      @tag_text
        .split(',')
        .map(&:strip)
        .select(&:present?)
    end
  end
end

app/models/site/article.rb
class Site::Article < Articles::Article
    default_scope -> { where(publishable: true).order(created_at: :desc) }

    def self.model_name
      Articles::Article.model_name
    end

    def self.sti_name
      Articles::Article.sti_name
    end

    def category_color
      return self.category.parent_category.color if self.category.parent_category.present?
      ''
    end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController
  defaults resource_class: Articles::ArticleWithImageCover
  load_and_authorize_resource(
    class: 'Articles::ArticleWithImageCover'
  )

  layout 'carnival/admin'

  def table_items
    Articles::Article.includes(:category, :user, :original_author)
  end

  def show
    if current_user.site_user?
      redirect_to post_path(params[:id])
    else
      super
    end
  end

  def create
    create! do |success, failure|
      success.html do
        flash[:notice] = I18n.t('messages.created')
        redirect_to action: :edit, id: @article.id
      end
      failure.html { instantiate_model && render('new') }
    end
  end

  def update
    update! do |success, failure|
      success.html do
        flash[:notice] = I18n.t('messages.updated')
        redirect_to action: :edit
      end
      failure.html { instantiate_model && render('edit') }
    end
  end

  protected

  def create_resource(resource)
    @article = resource
    @article.save
  end

  def build_resource_params
    return if params[:articles_article].nil?
    [
      params.require(:articles_article).permit(
        :text, :title, :intro_text, :category_id, :user_id,
        :original_author_id, :gender, :teenage_pregnancy, :baby_target_type,
        :publishable, :cover_picture_id, :thumb_picture_id, :box, :minimum_valid_week,
        :maximum_valid_week, :tag_names,
        article_references_attributes: [:id, :source, :_destroy],
        messages_attributes: [:id, :text, :father_text, :_destroy]
      ).merge(user_id: current_user.id)
    ]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @presenter = ArticlesPresenter.new(post_search_params, params[:order], current_user)
  end

  def show
    @article = ArticlePresenter.new(Site::Article.friendly.find(params[:id]))
    render layout: 'single-post'
  end

  def raw
    @article = ArticlePresenter.new(Site::Article.friendly.find(params[:id]))
    render layout: 'raw-single-post'
  end

  protected

  def post_search_params
    params.slice(:search, :category_id, :tag_name, :life_period, :page, :author_id)
  end
end

app/helpers/article_helper.rb
module ArticleHelper

  def show_image_class
    "hide" if @model.cover.blank?
  end

end

app/views/articles/_article.html.haml
.post.col-md-6{ class: article.category_type }

  %h2.post-title= link_to article.title, article_path(article)
  %p.periodo-label{ class: "period-#{article.pregnancy_or_child_life_period}" }
    = t("views.blog.#{article.pregnancy_or_child_life_period}")
  %p.categoria-label{ style: "background-color: #{article.category_color}" }= article.category_name
  %figure
    %img{width: 300, height: 200, src: article.thumb_image_cover.url(:content)}
  %p.post-summary
    = article.post_summary
  = link_to article_path(article), class: 'btn btn-primary education-button btn-list' do
    = t('views.blog.read_more')

  .social-share-button-wrapper
    .social-share-button-lines
      = social_share_button_tag(article.title, popup: true, :url => article_url(article),  :'data-type' => '')

app/views/articles/_article_for_period.html.haml
%nav.blog-time-range
  %ul.home-categories-list.category-education
    %h3
      período
    %li.home-categories-item.time-01
      = link_to t('views.blog.pregnancy'),
        articles_path(life_period: 'pregnancy')
    %li.home-categories-item.time-02
      = link_to t('views.blog.first_to_fourth'),
        articles_path(life_period: 'first_to_fourth')
    %li.home-categories-item.time-03
      = link_to t('views.blog.fifth_to_eighth'),
        articles_path(life_period: 'fifth_to_eighth')
    %li.home-categories-item.time-04
      = link_to t('views.blog.nineth_to_twelfth'),
        articles_path(life_period: 'nineth_to_twelfth')
    %li.home-categories-item.time-05
      = link_to t('views.blog.thirteenth_to_eighteenth'),
        articles_path(life_period: 'thirteenth_to_eighteenth')

app/views/articles/_disqus.html.haml
#disqus_thread
:javascript
  /* * * CONFIGURATION VARIABLES * * */
  var disqus_shortname = '#{Rails.application.config.disqus_shortname}';

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
%noscript
  Please enable JavaScript to view the
  %a{:href => "https://disqus.com/?ref_noscript", :rel => "nofollow"} comments powered by Disqus.

app/views/articles/_related_article.html.haml
.related-post.col-md-4
  %p
    %figure
      %img{width: 300, height: 200, src: related_article.thumb_image_cover.url(:content)}
  %p
    = link_to related_article.title, article_path(related_article)
  %p= related_article.post_summary

app/views/articles/index.html.haml
%section.subjects.container
  .posts.subject.col-md-9
    -if @presenter.articles.empty?

      .row
        .col-md-12.col-sm-12.not-found-box
          = image_tag 'not-found.svg'
          %h2= t 'views.articles.no_result'

    - else
      = render partial: 'article', collection: @presenter.articles

      %ul.pager.col-md-12
        - if @presenter.render_next_step?
          %li.previous
            = link_to t('views.blog.older_html'), @presenter.previous_blog_page
        - if @presenter.render_previous_step?
          %li.next
            = link_to t('views.blog.newer_html'), @presenter.next_blog_page

  = render 'sidebar',
    tags: @presenter.tags_for_sidebar,
    categories: @presenter.categories_for_sidebar,
    show_page: false

app/views/articles/raw.html.haml
.site-banner
  %ul.site-banner-list
    %li.site-banner-item
      %figure.site-banner-image{ style: "background-image: url(#{@article.cover})" }
        %img{ src: @article.cover }
    %li.site-banner-item
      %figure.site-banner-image{ style: "background-image: url(#{@article.cover})" }
        %img{ src: @article.cover }

%section.main.container-fuild.raw-container
  %section.subjects.container{ class: @article.category_name.parameterize }
    .raw-single-post.single-post.col-md-12
      %h2.post_title= @article.title
      %h5
        %i= @article.intro_text
      %p.periodo-label{ class: "period-#{@article.pregnancy_or_child_life_period}" }
        = t("views.blog.#{@article.pregnancy_or_child_life_period}")
      %p.categoria-label{ style: "background-color: #{@article.category_color}" }= @article.category_name
      %hr
      %p= raw @article.text

      = render @article.tags
      %hr
      %p.lead
        = t('views.blog.by', author: @article.author_name)

app/views/articles/show.html.haml
= render partial: 'meta_tag', article: @article

.site-banner
  %ul.site-banner-list
    %li.site-banner-item
      %figure.site-banner-image{ style: "background-image: url(#{@article.cover})" }
        %img{ src: @article.cover }


%section.main.container-fuild
  %section.subjects.container{ class: @article.category_type }
    .posts.subject.col-md-9
      .single-post.col-md-12
        .single-post-header
          %h2.post_title= @article.title
          %h5
            %i= @article.intro_text
          %p.periodo-label{ class: "period-#{@article.pregnancy_or_child_life_period}" }
            = t("views.blog.#{@article.pregnancy_or_child_life_period}")
          %p.categoria-label{ style: "background-color: #{@article.category_color}" }= @article.category_name
        %p
          = raw @article.text


        %ul.pager
          %li.previous
            = link_to t('views.blog.back_html'), root_path

        .row.single-post-info
          .single-post-tags.col-md-12
            %figure
            = render @article.tags

          .single-post-author.col-md-12
            %img.img-author{src: @article.author_photo_url}
            .single-post-author-info{ class: ("valign-middle" if @article.author_bio.empty?)}
              = t('views.blog.by', author: ' ')
              = link_to @article.author_name, articles_path(author_id: @article.original_author_id)
              .single-post-author-description
                = @article.author_bio


        - if current_user.nil?
          .signup-banner-footer
            %a{href: '/#sign-up'}
              %figure
              %label
                %b
                  Cadastre-se
                e receba mensagens
                %b
                  gratuitas
                em seu celular!


        .social-share-button-wrapper
          %p
            Compartilhe
          .social-share-button-lines
            = social_share_button_tag(@article.title, popup: true, :'data-type' => '')


        - if @article.related_articles.size > 0
          %p
            %h4= t('views.blog.related_post')
            = render partial: 'related_article', collection: @article.related_articles

        %p
          = render 'articles/disqus'

    = render 'sidebar',
      tags: @article.tags_for_sidebar,
      categories: @article.categories_for_sidebar,
      show_page: true,
      article: @article