config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  root to: 'home#index'

  match ':status', to: 'errors#show', constraints: { status: /\d{3}/ }, via: [:get, :post]
  resource :profile, except: :index do
    get :active
    get :disable
  end
  resources :timelines, only: :show
  get 'timelines/:id/monthly/:date' => 'timelines#monthly', as: :timeline_monthly
  constraints(id: /\d+/) do
    resources(:posts, only: [:show, :index])
  end
  resources(:articles, only: [:show, :index]) do
    collection do
      scope :categories do
        get ':category_id', to: 'articles#index', as: :categories
      end
    end
    get :raw, on: :member
  end

  resources :partners, only: :show
  get 'articles/page/:page_id' => 'articles#index', as: :paged_articles
  resources(:tags, param: :name, only: []) { resources :articles, only: :index }
  resources(:categories) { resources :articles, only: :index }
  get :colaborators, to: 'static_pages#colaborators'
  resources :authors, only: :show
  resources :pages, only: :show
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  namespace :api do
    resources :credentials, only: :create
    post 'credentials/update_social_network_id' => 'credentials#update_social_network_id'
    post 'check_numbers' => 'message_deliveries#check_numbers'
    resources :device_registrations, only: [:create, :show, :destroy], id: /[^\/]+/, param: :platform_code
    resources :messages, only: :show
    resources :profiles, only: [:index]
    get 'active_profile' => 'profiles#active'
    get 'disable_profile' => 'profiles#disable'
    post 'profiles/max_recipient_children' => 'profiles#update_max_recipient_children'
    post "profiles" => 'profiles#update'
    resources :donated_messages, only: [:index]
    post 'donated_messages/mark_as_sent' => 'donated_messages#mark_as_sent'
    resources :children, only: :index
    post 'd3d4b74ea38c163c820cd84b25f5/a8eecbf2d604ff6769fd64f1a492' => 'message_deliveries#create'
    devise_scope :user do
      post "/users" => 'users#create'
      post '/users/reset_password' => 'passwords#create'
    end
    get 'birthday_cards/show' => 'birthday_cards#show'
    get 'only_new_messages' => 'messages#only_new'
    resources :categories, only: [:index]
  end

  mount_carnival_at 'admin'
  namespace :admin do
    authenticate :user, ->(u) { u.admin? }  do
      mount Sidekiq::Web => '/sidekiq'
    end
    resources :activity_logs, only: [:index, :show]
    resources :admin_site_users
    resources :articles
    resources :posts
    resources :authors
    resources :categories
    resources :messages
    resources :message_deliveries, only: :index
    resources :profiles
    resources :site_banners
    resources :site_headers
    resources :site_landing_pages
    resources :site_mobile_images
    resources :partners
    resources :site_users do
      get :authorize_receive_sms, on: :member
      get :unauthorize_receive_sms, on: :member
      get :active_profile, on: :member
      get :disable_profile, on: :member
    end
    resources :tags
    resources :birthday_cards
    resources :pages
    resources :menus
    resources :engines
    resources :manager_message_deliveries, only: :index
    resources :searchlogs
    resources :sms_responses
    get 'articles/:id/show_activity_log' => 'articles#show_activity_log'
    get 'site_users/:id/stop_impersonating' => 'site_users#stop_impersonating', as: :stop_impersonating
    get 'admin_site_users/:id/edit_profile' => 'admin_site_users#edit_profile', as: :edit_profile
    get 'site_users/:id/impersonate' => 'site_users#impersonate', as: :impersonate_user

    get 'gallery_images' => 'gallery_images#index'

    post 'new_image' => 'cms_images#create'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @categories_articles = articles_grouped_by_category
    else
      @categories = Category.to_show_in_home
    end
  end

  protected

  def articles_grouped_by_category
    Site::CategoryGroupedArticlesFinder.new.find.map do |category, articles|
      [category, ArticlePresenter.wrap(articles)]
    end
  end


end

app/views/home/_signed_in.html.haml
= render 'home_categories'

%section.subjects.container.signed-in
  - @categories_articles.each do |category, articles|
    .subject.col-md-9{ id: category.slug }
      .row.col-md-12
        = render "subject_header", category: category
      - articles.each do |article|
        .col-md-6
          .subject-picture-split
            = link_to article_path(article) do
              %figure
                %img{ width: 300, height: 200, src: article.thumb_image_cover.url(:content)}
            .subject-picture-split-description
              = link_to article_path(article) do
                %p= article.post_summary
      = link_to categories_articles_path(category) do
        %button.subject-picture-split-see-all-posts.center-block{ style: "background-color: #{category.color}" }
          = t('views.application.show_all_post_from_this_category')

app/views/home/_subject.html.haml
.subject.col-md-9{ id: subject }
  .row.col-md-12= render "subject_header", category: category

  .col-md-5
    .subject-picture.subject-picture-back-shadow
      %figure{ style: "background-image: url(#{category.category_image.url})" }
        %img
      .subject-picture-description
        = raw category.category_image_text
  .col-md-7
    .subject-description
      .subject-description-header{ class: "subject-description-header-#{subject}" }
        %h3= raw category.subtitle
        %p= raw category.text
    .subject-description-buttons
      %button.sign-up{ style: "background-color:#{category.color}; color:#fff", class: "subject-description-buttons-sign-in" , data: { color1: "#{category.color}", color2: "#fff" } }
        = t('views.home.anonymous.sign_up')
      = link_to category ? categories_articles_path(category_id: category) : '#' do
        %button{ style: "background-color:#fff; color:#{category.color}", class: "subject-description-buttons-read", data: { color1: '#fff', color2: "#{category.color}" } }
          = t('views.home.anonymous.read')

app/views/home/index.html.haml
= javascript_include_tag 'jquery-scrolltofixed'

.clearfix
- if current_user
  = render 'signed_in'
- else
  = render 'anonymous'

app/views/home/subject.html.haml
.subject.col-md-9{ id: subject }
  .row.col-md-12= render "subject_header_#{subject}"

  .col-md-5
    .subject-picture.subject-picture-back-shadow
      %figure
        %img
      .subject-picture-description
        %p= t("views.home.anonymous.#{subject}.picture_legend")
  .col-md-7
    .subject-description
      .subject-description-header{ class: "subject-description-header-#{subject}" }
        %h3= t("views.home.anonymous.#{subject}.header_html")
        %p= t("views.home.anonymous.#{subject}.description")
    .subject-description-buttons
      %button.sign-up{ class: "subject-description-buttons-sign-in-#{subject}" }
        = t('views.home.anonymous.sign_up')
      = link_to posts_path(category: subject) do
        %button{ class: "subject-description-buttons-read-#{subject}" }
          = t('views.home.anonymous.read')