config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  root to: 'home#index'

  match ':status', to: 'errors#show', constraints: { status: /\d{3}/ }, via: [:get, :post]
  resource :profile, except: :index do
    get :active
    get :disable
  end
  resources :timelines, only: :show
  get 'timelines/:id/monthly/:date' => 'timelines#monthly', as: :timeline_monthly
  constraints(id: /\d+/) do
    resources(:posts, only: [:show, :index])
  end
  resources(:articles, only: [:show, :index]) do
    collection do
      scope :categories do
        get ':category_id', to: 'articles#index', as: :categories
      end
    end
    get :raw, on: :member
  end

  resources :partners, only: :show
  get 'articles/page/:page_id' => 'articles#index', as: :paged_articles
  resources(:tags, param: :name, only: []) { resources :articles, only: :index }
  resources(:categories) { resources :articles, only: :index }
  get :colaborators, to: 'static_pages#colaborators'
  resources :authors, only: :show
  resources :pages, only: :show
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  namespace :api do
    resources :credentials, only: :create
    post 'credentials/update_social_network_id' => 'credentials#update_social_network_id'
    post 'check_numbers' => 'message_deliveries#check_numbers'
    resources :device_registrations, only: [:create, :show, :destroy], id: /[^\/]+/, param: :platform_code
    resources :messages, only: :show
    resources :profiles, only: [:index]
    get 'active_profile' => 'profiles#active'
    get 'disable_profile' => 'profiles#disable'
    post 'profiles/max_recipient_children' => 'profiles#update_max_recipient_children'
    post "profiles" => 'profiles#update'
    resources :donated_messages, only: [:index]
    post 'donated_messages/mark_as_sent' => 'donated_messages#mark_as_sent'
    resources :children, only: :index
    post 'd3d4b74ea38c163c820cd84b25f5/a8eecbf2d604ff6769fd64f1a492' => 'message_deliveries#create'
    devise_scope :user do
      post "/users" => 'users#create'
      post '/users/reset_password' => 'passwords#create'
    end
    get 'birthday_cards/show' => 'birthday_cards#show'
    get 'only_new_messages' => 'messages#only_new'
    resources :categories, only: [:index]
  end

  mount_carnival_at 'admin'
  namespace :admin do
    authenticate :user, ->(u) { u.admin? }  do
      mount Sidekiq::Web => '/sidekiq'
    end
    resources :activity_logs, only: [:index, :show]
    resources :admin_site_users
    resources :articles
    resources :posts
    resources :authors
    resources :categories
    resources :messages
    resources :message_deliveries, only: :index
    resources :profiles
    resources :site_banners
    resources :site_headers
    resources :site_landing_pages
    resources :site_mobile_images
    resources :partners
    resources :site_users do
      get :authorize_receive_sms, on: :member
      get :unauthorize_receive_sms, on: :member
      get :active_profile, on: :member
      get :disable_profile, on: :member
    end
    resources :tags
    resources :birthday_cards
    resources :pages
    resources :menus
    resources :engines
    resources :manager_message_deliveries, only: :index
    resources :searchlogs
    resources :sms_responses
    get 'articles/:id/show_activity_log' => 'articles#show_activity_log'
    get 'site_users/:id/stop_impersonating' => 'site_users#stop_impersonating', as: :stop_impersonating
    get 'admin_site_users/:id/edit_profile' => 'admin_site_users#edit_profile', as: :edit_profile
    get 'site_users/:id/impersonate' => 'site_users#impersonate', as: :impersonate_user

    get 'gallery_images' => 'gallery_images#index'

    post 'new_image' => 'cms_images#create'
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  load_and_authorize_resource class: 'Child'
  layout 'timeline'

  before_action :authenticate_user!
  before_action :load_timeline

  def show
    period = MessageDeliveryTimelineDecorator.default_period
    @timeline = MessageDeliveryTimelineDecorator.timeline(@child, period)
  end

  def monthly
    month = DateTime.parse(params[:date])
    period = MessageDeliveryTimelineDecorator.month_period(month)
    @timeline = MessageDeliveryTimelineDecorator.timeline(@child, period)
    @timeline_month = TimelineMonth.new(month.to_date)

    respond_to do |format|
      format.js
    end
  end

  protected

  def load_timeline
    @child = Child.find(params[:id])
    @timeline_step = TimelineStep.new
    @month_step = TimelineStep.new
  end
end

app/helpers/timeline_helper.rb
module TimelineHelper
  def definition_list_item(definition_term, description)
    content_tag(:dt) { definition_term } +
      content_tag(:dd) { description }
  end
end

app/views/timelines/_show_monthly.html.haml
.timeline-start
%ul.timeline
  = render @timeline.timeline_days

app/views/timelines/_timeline_day.html.haml
%li.timeline-steps{class: "step-#{@timeline_step.next_step}", id: dom_id(timeline_day)}
  .day-data
    .day= l timeline_day.date, format: :day
    .month= l timeline_day.date, format: :month_name
    .year= l timeline_day.date, format: :full_year
    %ul.timeline-step-bullets
      %li
        %a{href: '#'}
  - if timeline_day.has_event?
    .entry
      %p= link_to timeline_day.event_content, timeline_day.event_url
      .social-share-button-wrapper-timeline
        .social-share-button-lines-timeline
          - path = "#{request.protocol}#{request.host_with_port}#{timeline_day.event_url}"
          = social_share_button_tag(timeline_day.event_content, popup: true, :url => path,  :'data-type' => '')

app/views/timelines/_timeline_month.html.haml
%li.timeline-month{class: "month-step-#{@month_step.next_step}", id: dom_id(timeline_month)}
  = link_to l(timeline_month.date, format: :month_name_year), timeline_monthly_path(@child, date: timeline_month.date), remote: true, :format => :js
  .month-timeline

app/views/timelines/monthly.js.erb
$(".month-timeline").empty();
$("#<%= dom_id(@timeline_month) %> .month-timeline").html("<%= j render(partial: 'show_monthly') %>");
$(window).scrollTo("#<%= dom_id(@timeline_month) %>", 1000)

app/views/timelines/show.html.haml
= content_for :head do
  = stylesheet_link_tag "timeline"
  = javascript_include_tag "timeline"

.timeline-start
%ul.timeline
  = render @timeline.timeline_days

%ul.timeline-months
  = render @timeline.timeline_months